CREATE TABLE IF NOT EXISTS `simple_posts`.`posts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `iduser` BIGINT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `text` MEDIUMTEXT NOT NULL,
    `createdat` DATETIME NOT NULL,
    FOREIGN KEY (iduser) REFERENCES users(id) ON DELETE CASCADE
)